#!/bin/env bash

github_profile="NikosGour"

# get params to get project name
project_name=""

usage() {
	printf "Usage: go_init [option] project_name\n\n\t-g\tIf you are planning on publishing on github. Make sure to change your github username in the script\n"
}

github_flag=false

# if no arguments pass print usage
if [ "$1" == "" ]; then
	usage
	exit 1
fi

while [ "$1" != "" ]; do
	case $1 in
	-g)
		github_flag=true
		;;
	# release)
	# 	release_flag=true
	# 	;;
	# clean)
	# 	clean_flag=true
	# 	;;
	*)
		project_name=$1
		;;
	esac
	shift
done

mkdir $project_name
cd $project_name
if [ $github_flag == true ]; then
	git init
	go mod init github.com/$github_profile/$project_name
else
	go mod init $project_name
fi
mkdir src out
printf "out/" >.gitignore

printf "package main\nimport \"fmt\"\nfunc main(){\nfmt.Println(\"Hello World\")\n}" >src/main.go

printf "#!/bin/env bash\ngo build -o out/$project_name src/main.go" >build.sh
chmod +x build.sh
