#!/bin/bash

read -p "Are you sure you want to remove all files in the current directory? (y/n) " answer
if [ $answer = "y" ];then
	find -maxdepth 1 -regex './.+' | xargs rm -r
else
	echo "Aborted"
fi