#!/bin/bash
Red='\033[0;31m'    
Color_Off='\033[0m'       


printf "${Red}Are you sure you want to remove all files in the current directory? (y/n) ${Color_Off}"

# read -p "Are you sure you want to remove all files in the current directory? (y/n) " answer
# if [ $answer = "y" ];then
# 	find -maxdepth 1 -regex './.+' | xargs rm -r
# else
# 	echo "Aborted"
# fi