#!/bin/bash
Red='\033[0;31m'    
Color_Off='\033[0m'       

pwd=`echo $PWD | rev | cut -d '/' -f 1 | rev`
files=`find -maxdepth 1 -regex './.+'| sed "s|\.\/|${pwd}\/|"`
echo -e "${Red}${files}${Color_Off}"
read -p "Are you sure you want to remove all files in the current directory? (y/n) " answer
if [ $answer = "y" ];then
	find -maxdepth 1 -regex './.+' | xargs rm -r
else
	echo "Aborted"
fi